version: "3"

services: 
  adminer:
    image: adminer
    expose:
      - 8080
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: ${USER}
        userid: ${USERID}
        dockergid: ${DOCKERGID}
    image: ${USER}-symfony-docker
    hostname: ${USER}-symfony

    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity