name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          cd .docker

          echo "USERID=$(id -u)" > .env
          echo "DOCKERGID=$(getent group docker | cut -d: -f3)" >> .env
          echo "USER=${USER}" >> .env

          docker compose build app
